dist: xenial
sudo: false
latex: false
language: r
r:
  - 3.4

warnings_are_errors: false
cache:
  directories: $TRAVIS_BUILD_DIR/packrat/
  packages: true

install:
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"
  
git:
  depth: false

after_success:
  - Rscript -e 'rsconnect::setAccountInfo(name="rafaelschlatter", token=Sys.getenv("shinyapps_token"), secret=Sys.getenv("shinyapps_secret"))'
  - Rscript -e 'rsconnect::deployApp()'
