dist: xenial
sudo: false
latex: false
language: r
r:
  - 3.4

warnings_are_errors: false
cache:
  directories: $TRAVIS_BUILD_DIR/packrat/
  packages: true

before_install:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get update
  - sudo apt-get install libjq-dev
  - sudo apt-get install libv8-dev

install:
  - R -e "0" --args --bootstrap-packrat
  
git:
  depth: false

after_success:
  - Rscript -e "install.packages('rsconnect')"
  - Rscript -e 'rsconnect::setAccountInfo(name="rafaelschlatter", token=Sys.getenv("shinyapps_token"), secret=Sys.getenv("shinyapps_secret"))'
  - Rscript -e 'rsconnect::deployApp()'
