dist: xenial
sudo: false
latex: false
language: r
r:
  - 3.4

warnings_are_errors: false
cache: packages
r_packages:
  - shiny,
  - flexdashboard,
  - jsonlite,
  - highcharter,
  - dplyr,
  - tidyr,
  - knitr,
  - rsconnect,
  - rStrava
#remotes: fawda123/rStrava

apt_packages:
  - libgdal-dev
  - libudunits2-dev
  
git:
  depth: false
  
script:
  - R -f deploy.R