dist: xenial
sudo: false
latex: false
language: r
r:
  - 3.4

warnings_are_errors: false
cache:
  directories: $TRAVIS_BUILD_DIR/packrat/
  packages: true

install:
  - R -e "install.packages('devtools')"
  - R -e "devtools::install_github('fawda123/rStrava')"
  - R -e "install.packages('flexdashboard', 'jsonlite', 'highcharter', 'dplyr', 'tidyr', 'knitr', 'htmltools')"
  
git:
  depth: false

after_success:
  - Rscript -e 'rsconnect::setAccountInfo(name="rafaelschlatter", token=Sys.getenv("shinyapps_token"), secret=Sys.getenv("shinyapps_secret"))'
  - Rscript -e 'rsconnect::deployApp()'
