---
title: "Strava-flex"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: https://github.com/rafaelschlatter/strava-flex
    social: menu
#runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(rStrava)
library(jsonlite)
library(ggplot2)
library(ggthemes)
library(plotly)
library(highcharter)
library(dplyr)

strava_keys = fromJSON('keys.json')$strava
strava_goals = fromJSON('keys.json')$goals
stoken <- httr::config(token = strava_oauth(strava_keys$app_name,
                                            strava_keys$client_id,
                                            strava_keys$client_secret))

activities <- get_activity_list(stoken)
athlete <- get_athlete(stoken)
df <- compile_activities(activities)
df$row <- seq.int(nrow(df))
df$calendar_date <- as.Date(df$start_date)
df$calendar_year <- lubridate::year(df$start_date)
df$calendar_month <- lubridate::month(df$start_date)
df$calendar_week <- lubridate::week(df$start_date)
df$weekday <- weekdays(as.Date(df$start_date))

yearly_activites <- subset(df, calendar_date > as.Date("2018-12-31"))
```

Sidebar {.sidebar}
=======================================================================
### Athlete Information
**First name**: `r athlete$firstname`  
**Last name**: `r athlete$lastname`  
**City**: `r athlete$city`  
**Country**: `r athlete$country`  


Year-to-date statistics {data-icon="fa-chart-bar"}
=======================================================================
Row
-----------------------------------------------------------------------
### Yearly goal
Your current yearly km goal is set to `r strava_goals$yearly_km`km.  
  
  
```{r}
current_distance = round(sum(yearly_activites$distance), digits = 1)

first = strava_goals$yearly_km / 3
second = first * 2

gauge(current_distance, min = 0, max = strava_goals$yearly_km, symbol = 'km', gaugeSectors(
  success = c(second+1, strava_goals$yearly_km), warning = c(first+1, second), danger = c(0, first)
))
```

### Weekly activity minutes
Your current weekly activity goal is set to `r strava_goals$weekly_min` min.  
  
  
```{r}
current_date <- Sys.Date()
current_day <- weekdays(current_date)

if (current_day == "Monday") {
  weekstart <- current_date
} else if (current_day == "Tuesday") {
  weekstart <- current_date - 1
} else if (current_day == "Wednesday") {
  weekstart <- current_date - 2
} else if (current_day == "Thursday") {
  weekstart <- current_date - 3
} else if (current_day == "Friday") {
  weekstart <- current_date - 4
} else if (current_day == "Saturday") {
  weekstart <- current_date - 5
} else {
  weekstart <- current_date - 6
}

weekly_activites = subset(df, calendar_date > weekstart)
weekly_min = round(sum(weekly_activites$elapsed_time) / 60)

first = strava_goals$weekly_min / 3
second = first * 2

gauge(weekly_min, min = 0, max = strava_goals$weekly_min, symbol = 'min', gaugeSectors(
  success = c(second+1, strava_goals$weekly_min), warning = c(first+1, second), danger = c(0, first)
))
```

### Activities by type
```{r}
activity_types <- as.data.frame(table(yearly_activites$type))
activity_types$Var1 <- factor(activity_types$Var1)

tooltip <- JS("function(){
  return this.point.x + ':<br/>' +
  this.y + ' activities<br/>' +
  Highcharts.numberFormat(this.percentage, 2) + '%<br />';
}")

hc <- highchart() %>% 
  hc_chart(type = "pie") %>% 
  hc_add_series(name = "Activity type", data = activity_types$Freq) %>%
  hc_yAxis(categories = activity_types$Var1) %>%
  hc_tooltip(formatter = tooltip) %>%
  hc_add_theme(hc_theme_google())

hc
```

Row
-----------------------------------------------------------------------
### Monthly distance (all activity types)
```{r}
monthly_dist <- aggregate(yearly_activites$distance, list(yearly_activites$calendar_month), sum, na.rm = TRUE)

hc <- highchart() %>% 
  hc_chart(type = "bar") %>% 
  hc_xAxis(categories = c("Januar", "Februar", "March", "April", "May", "June",
                          "July", "August", "September", "October", "November", "December")) %>% 
  hc_yAxis(min = 0, title = list(text = "Total distance in km")) %>%
  hc_add_series(name = "Distance (km)", data = monthly_dist$x) %>%
  hc_add_theme(hc_theme_google())

hc
```

### Activity heatmap
```{r}
heatmap_data <- group_by(yearly_activites, calendar_week, weekday) %>% summarize(dist = sum(distance))
heatmap_data$weekday <- factor(heatmap_data$weekday, levels = c("Monday", "Tuesday", "Wednesday",
                                                                "Thursday", "Friday", "Saturday", "Sunday"))

tooltip <- JS("function(){
  return 'Week ' + this.point.x + ', ' +  this.series.yAxis.categories[this.point.y] + ':<br>' +
  'Distance: ' + Highcharts.numberFormat(this.point.value, 2) + 'km';
}")

hc <- hchart(heatmap_data, "heatmap", hcaes(x = calendar_week, y = weekday, value = dist)) %>%
  hc_xAxis(title = list(text = "Calendar week")) %>%
  hc_tooltip(formatter = tooltip) %>%
  hc_add_theme(hc_theme_google())
hc
```